/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_A */

#ifndef _Included_com_A
#define _Included_com_A
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_A
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_A_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
